language: csharp
solution: Travis-test.sln
install:
  - nuget restore Travis-test.sln
  - nuget install NUnit.Runners -Version 2.6.4 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release Travis-test.sln
  - mono ./testrunner/NUnit.Runners.2.6.4/tools/nunit-console.exe ./HelloWorld/bin/Release/HelloWorld.Tests.dll