sudo: required

language: csharp
solution: Travis-test.sln
mono: 
  - latest

services: 
  - docker

install:
  - nuget restore
  - nuget install NUnit.Runners -Version 2.6.4 -OutputDirectory testrunner

script:
  - xbuild /p:Configuration=Release
  - mono ./testrunner/NUnit.Runners.2.6.4/tools/nunit-console.exe ./HelloWorld.Tests/bin/Release/HelloWorld.Tests.dll